---
title: "Lab mtg example plots"
date: "`r Sys.Date()`"
output: html_document
runtime: shiny
---


## Example plots page
```{r eval =TRUE, echo=FALSE, message = FALSE, warning = FALSE }
############## SMALL SPATIAL SCALES ONLY ##############
library(tidyverse)
library(chorddiag)
library(gdata)

df<- read.csv("example_categories.csv", header = TRUE)
out_gen1 <- crossprod(table(subset(stack(setNames(lapply(strsplit(df$Category, 
                                                                 ",\\s*"), trimws), df$Id))[2:1],nzchar(values))))
diag(out_gen1) <- 0

#Make interactive plots
cols_g <- c("#FFBBFF","#B3EE3A", "#3A5FCD", "#009E73","#FFA07A","#6EE2FF",
           "#00008B")


plt <- chorddiag(out_gen1, groupColors = cols_g, showGroupnames = FALSE,groupPadding = 2,showTooltips = TRUE,precision=3,showZeroTooltips = FALSE,tickInterval=10,ticklabelFontsize=0,groupnamePadding = 0,width = 350, height=350, margin=10)

# Define titles for each graph
title_plt <- "A plot"

# Create div layout with custom CSS and titles
layout <- tags$div(
  class = "layout-container",
  tags$div(
    class = "graph-container",
    tags$h1(title_plt),  # Add title for graph p1
    plt
  )
)

```

```{r eval =TRUE, echo=FALSE, message = FALSE, warning = FALSE}
library(shinydashboard)
order_gp <- cbind(names,cols_g)
ui <- fluidPage(
  dashboardBody(
    tags$head(
      tags$style(
        HTML("
          body {overflow-y: hidden;}
          .graph-container h1 {
            width: 100%;
            font-size: 30px;
            margin-top: 20px; 
          }
          .layout-container {
            padding-top: 0;
          }
        ")
      )
    ),
    fluidRow(
      column(width = 6,
             layout  # Add the static layout here
      ),
      column(width = 6, class = "shiny-app-container",
             tags$div(
               class = "shiny-app-title",
               tags$h2("Filtered plots")
             ),
             sidebarLayout(
               sidebarPanel(
                 uiOutput("selected_taxa1"),
                 div(actionButton("add_plot1", "Plot"))
               ),
               mainPanel(
                 chorddiag::chorddiagOutput("chordDiagram1")
               )
             )
      )
    )
  )
)

server <- function(input, output, session) {
  taxa_list <- reactive({
    unique(names)
  })
  
  # This function give us a select list input, in order to be able to select the gene that we want to see
  output$selected_taxa1 <- renderUI({
    selectizeInput(inputId = "taxa", "Select a letter", choices=taxa_list(), options=list(maxOptions = length(taxa_list())))
  })
  
  mydata <- reactive({
    req(input$taxa)
      df <- df %>% 
        filter(str_detect(Category, pattern = input$taxa))
      out_df <- crossprod(table(subset(stack(setNames(lapply(strsplit(df$Category, 
                                                                 ",\\s*"), trimws), df$Id))[2:1], nzchar(values))))
      diag(out_df) <- 0
      custom_order_f <- intersect(names,colnames(out_df))
      out_df <- out_df[custom_order_f, custom_order_f]
      out_df
  })


  use_cols <- reactive({
  req(input$taxa)
  out_df <- crossprod(table(subset(stack(setNames(lapply(strsplit(df$Category, 
                                                           ",\\s*"), trimws), df$Id))[2:1], nzchar(values))))
  diag(out_df) <- 0
  out_df <- out_df[names, names]
  cols <- subset((order_gp[,2]), names %in% colnames(out_df))
  cols
})
  
  v <- reactiveValues(plot = NULL, table=NULL)
  
  observeEvent(input$add_plot1, {
     output$chordDiagram1 <- renderChorddiag({ chorddiag::chorddiag(mydata(), groupColors = use_cols(), showGroupnames = FALSE, groupPadding = 2,showTooltips = TRUE,precision=3, showZeroTooltips = FALSE,tickInterval=10,ticklabelFontsize=0,groupnamePadding = 0,width = 550, height=350, margin=10)
     })
  })
  output$staticPlot <- renderPlot({plt
  })
}

shinyApp(ui, server,options = list(width = 1300, height=600))
```

<div style="width: 500%;">
```{r eval =TRUE, echo=FALSE, message = FALSE, warning = FALSE }
legend_colors <- c("#FFBBFF","#B3EE3A", "#3A5FCD", "#009E73","#FFA07A","#6EE2FF","#00008B")
names <- c("A","B","C","D","E","F","G")
n<-length(names)
plot_legend <- function(names, legend_colors) {
  plot(0, 0, type = "n", axes = FALSE, xlab = "", ylab = "",
       xlim = c(0, 1), ylim = c(0, 1))
  for (i in 1:length(names)) {
    rect(0.1, 1 - i * 0.1, 0.2, 1 - (i - 1) * 0.1,
         col = legend_colors[i], border = NA)
    text(0.3, 1 - (i - 0.5) * 0.1, names[i], adj = 0)
  }
}
par(mfrow = c(1, 4),mar = c(0, 0, 1, 0)) ;
plot_legend(names[1:n], legend_colors[1:n])
title("Legend", line = 0, adj = 0)  
```